name: CI-CD

on:
  - push
  - pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: ESLint
        run: yarn lint

  build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@master
    - name: Build and publish to registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: shaundeveloper/zecarioca
        tag_with_ref: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@master
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract
    - name: Extract docker tag
      shell: bash
      run: echo "##[set-output name=docker;]$(if [ "${{ steps.extract.outputs.branch }}" == "master" ]; then echo "latest"; else echo ${{ steps.extract.outputs.branch }}; fi)"
      id: tag
    - name: Run docker build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop ${{ steps.extract.outputs.branch }}
          docker rm ${{ steps.extract.outputs.branch }}
          docker pull shaundeveloper/zecarioca:${{ steps.tag.outputs.docker }}
          docker run --name ${{ steps.extract.outputs.branch }} --env-file ~/.env/${{ steps.extract.outputs.branch }}.env --restart unless-stopped -d shaundeveloper/zecarioca:${{ steps.tag.outputs.docker }}
          docker system prune -a -f
